#!/bin/sh

rm simulation_output.csv # clean simulation csv
parallel --verbose ::: "gunzip -c mcf.trace.gz | ./cache.exe -t 16 -a 1 -l 16 --rp RANDOM --mp 2 --csv mcf" "gunzip -c art.trace.gz | ./cache.exe -t 16 -a 1 -l 16 --rp RANDOM --mp 2 --csv art" "gunzip -c mcf.trace.gz | ./cache.exe -t 32 -a 1 -l 16 --rp RANDOM --mp 2 --csv mcf" "gunzip -c art.trace.gz | ./cache.exe -t 32 -a 1 -l 16 --rp RANDOM --mp 2 --csv art" "gunzip -c mcf.trace.gz | ./cache.exe -t 128 -a 1 -l 16 --rp RANDOM --mp 2 --csv mcf" "gunzip -c art.trace.gz | ./cache.exe -t 128 -a 1 -l 16 --rp RANDOM --mp 2 --csv art"
